---
- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
  become: true

- name: Debian/Ubuntu | Install ca-certificates and gnupg
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg
    state: present
  become: true
  register: wazuh_agent_ca_package_install
  until: wazuh_agent_ca_package_install is succeeded

- name: Debian/Ubuntu | Install apt-transport-https and acl
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - acl
    state: present
  become: true
  register: wazuh_agent_ca_package_install
  until: wazuh_agent_ca_package_install is succeeded
  when: not (ansible_distribution == "Debian" and ansible_distribution_major_version in ['11'])

- name: Debian/Ubuntu | Installing Wazuh repository key (Ubuntu 14)
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    curl -s {{ wazuh_agent_config.repo.gpg }} | apt-key add -
  args:
    # warn: false
    executable: /bin/bash
  changed_when: false
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version | int == 14
    - not wazuh_custom_packages_installation_agent_enabled

- name: Debian/Ubuntu | Download Wazuh repository key
  ansible.builtin.get_url:
    url: "{{ wazuh_agent_config.repo.gpg }}"
    dest: "{{ wazuh_agent_config.repo.path }}"
  become: true
  when:
    - not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int == 14)
    - not wazuh_custom_packages_installation_agent_enabled

- name: Debian/Ubuntu | Import Wazuh GPG key
  ansible.builtin.command: "gpg --no-default-keyring --keyring gnupg-ring:{{ wazuh_agent_config.repo.keyring_path }} --import {{ wazuh_agent_config.repo.path }}"
  become: true
  when:
    - not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int == 14)
    - not wazuh_custom_packages_installation_agent_enabled
  args:
    creates: "{{ wazuh_agent_config.repo.keyring_path }}"

- name: Debian/Ubuntu | Set permissions for Wazuh GPG key
  ansible.builtin.file:
    path: "{{ wazuh_agent_config.repo.keyring_path }}"
    mode: '0644'
  become: true
  when:
    - not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int == 14)
    - not wazuh_custom_packages_installation_agent_enabled

- name: Debian/Ubuntu | Add Wazuh repositories
  ansible.builtin.apt_repository:
    filename: wazuh_repo
    repo: "{{ wazuh_agent_config.repo.apt }}"
    state: present
  become: true
  when:
    - not wazuh_custom_packages_installation_agent_enabled

- name: Debian/Ubuntu | Set Distribution CIS filename for debian
  ansible.builtin.set_fact:
    cis_distribution_filename: cis_debian_linux_rcl.txt
  when: ansible_os_family == "Debian"

- name: Debian/Ubuntu | Install OpenJDK-21 repo
  ansible.builtin.apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present
    update_cache: true
    cache_valid_time: 0
  become: true
  when:
    - (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int == 14)

- when:
    - wazuh_agent_config.cis_cat.disable == 'no'
    - wazuh_agent_config.cis_cat.install_java == 'yes'
  block:
    - name: Debian/Ubuntu | Install OpenJDK 21
      ansible.builtin.apt:
        name: openjdk-21-jre
        state: present
        cache_valid_time: 0
  become: true
  tags:
    - init

- name: Debian/Ubuntu | Install OpenScap
  ansible.builtin.apt:
    name:
      - openscap-scanner
      - openscap-utils
      - xsltproc
    state: present
  become: true
  when: wazuh_agent_config.openscap.disable == 'no' and (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int <= 22)
  tags:
    - init
  register: wazuh_agent_OpenScap_package_install
  until: wazuh_agent_OpenScap_package_install is succeeded

- name: Debian/Ubuntu | Install OpenScap
  ansible.builtin.apt:
    name:
      - openscap-scanner
      - openscap-utils
      - xsltproc
    state: present
  become: true
  when: wazuh_agent_config.openscap.disable == 'no' and (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int == 24)
  tags:
    - init
  register: wazuh_agent_OpenScap_package_install
  until: wazuh_agent_OpenScap_package_install is succeeded

- name: Debian/Ubuntu | Get OpenScap installed version
  ansible.builtin.shell: "dpkg-query --showformat='${Version}' --show openscap-scanner"
  register: openscap_version
  changed_when: false
  when: wazuh_agent_config.openscap.disable == 'no'
  tags:
    - config

- name: Debian/Ubuntu | Check OpenScap version
  ansible.builtin.shell: "dpkg --compare-versions '{{ openscap_version.stdout }}' '>=' '1.2'; echo $?"
  register: openscap_version_valid
  changed_when: false
  when: wazuh_agent_config.openscap.disable == 'no'
  tags:
    - config

# Osquery installation
- name: Debian/Ubuntu | Installing Osquery repository key (Ubuntu >= 22)
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    curl -L https://pkg.osquery.io/deb/pubkey.gpg | sudo tee /etc/apt/keyrings/osquery.asc
  args:
    # warn: false
    executable: /bin/bash
  changed_when: false
  when:
    - ansible_distribution == "Ubuntu" and (ansible_distribution_major_version | int >= 22)
    - wazuh_agent_config.osquery.disable == 'no'
  tags:
    - init
  
- name: Add Osquery repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/osquery.asc] https://pkg.osquery.io/deb deb main"
    state: present
    update_cache: true
  when:
    - ansible_distribution == "Ubuntu" and (ansible_distribution_major_version | int >= 22)
    - wazuh_agent_config.osquery.disable == 'no'
  tags:
    - init

- name: Debian/Ubuntu | Install Osquery
  become: true
  ansible.builtin.apt:
    name: osquery
    state: present
  when:
    - ansible_distribution == "Ubuntu" and (ansible_distribution_major_version | int >= 22)
    - wazuh_agent_config.osquery.disable == 'no'
  tags:
    - init
  register: wazuh_agent_osquery_package_install
  until: wazuh_agent_osquery_package_install is succeeded

- name: Debian/Ubuntu | Copy Osquery configuration file
  become: true
  ansible.builtin.copy:
    src: osquery.conf
    dest: /etc/osquery/osquery.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_distribution == "Ubuntu" and (ansible_distribution_major_version | int >= 22)
    - wazuh_agent_config.osquery.disable == 'no'
  tags:
    - config

- name: Debian/Ubuntu | Enable Osquery service
  become: true
  ansible.builtin.systemd:
    name: osqueryd
    enabled: true
  when:
    - ansible_distribution == "Ubuntu" and (ansible_distribution_major_version | int >= 22)
    - wazuh_agent_config.osquery.disable == 'no'

- name: Debian/Ubuntu | Enable and start Osquery service
  become: true
  ansible.builtin.systemd:
    name: osqueryd
    state: started
  when:
    - ansible_distribution == "Ubuntu" and (ansible_distribution_major_version | int >= 22)
    - wazuh_agent_config.osquery.run_daemon == 'yes'
